# Generated by Django 5.0.9 on 2024-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vocab_name",
                    models.CharField(max_length=255, verbose_name="vocabulary"),
                ),
                ("uri", models.URLField(unique=True, verbose_name="URI")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="preferred label"),
                ),
            ],
            options={
                "verbose_name": "concept",
                "verbose_name_plural": "concepts",
            },
        ),
    ]
