# Generated by Django 5.1.6 on 2025-06-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_vocabs", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="concept",
            unique_together={("vocabulary", "name")},
        ),
    ]
